import { Target, Zap, Shield, LucideIcon } from "lucide-react"

export const HERO_CONTENT = {
  badge: "AI-Powered Detection",
  headline: "Detect AI-Generated Content in Seconds",
  subheadline:
    "Advanced AI detection technology that identifies ChatGPT, GPT-4, Claude, and other AI-generated text with 98% accuracy. Trusted by educators, content creators, and businesses worldwide.",
  primaryCTA: "Try Free Scan",
  secondaryCTA: "View Pricing",
  trustIndicators: ["No credit card", "Instant results", "Cancel anytime"],
}

export const FEATURES: Array<{
  icon: LucideIcon
  title: string
  description: string
}> = [
  {
    icon: Target,
    title: "98% Accuracy Rate",
    description:
      "Our advanced machine learning models analyze text patterns, sentence structures, and linguistic markers to provide the most accurate AI detection results in the industry. Continuously trained on the latest AI models including GPT-4, Claude, and Gemini.",
  },
  {
    icon: Zap,
    title: "Instant Results",
    description:
      "Get comprehensive analysis in under 3 seconds. Our real-time processing engine scans up to 50,000 characters instantly, providing detailed reports with highlighted AI-generated sections and confidence scores for each paragraph.",
  },
  {
    icon: Shield,
    title: "Complete Privacy",
    description:
      "Your content never leaves our secure servers and is deleted immediately after analysis. We don't store, share, or train our models on your submissions. GDPR compliant with enterprise-grade encryption for all data transmissions.",
  },
]

export const HOW_IT_WORKS = [
  {
    number: "01",
    title: "Paste Your Text",
    description:
      "Copy and paste the content you want to analyze into our detection tool. Supports plain text, documents, and URLs. No registration required for the first scan.",
  },
  {
    number: "02",
    title: "AI Analysis",
    description:
      "Our advanced algorithms scan the text using multiple detection models simultaneously. We analyze syntax patterns, vocabulary complexity, sentence flow, and AI-specific linguistic markers.",
  },
  {
    number: "03",
    title: "Get Detailed Report",
    description:
      "Receive a comprehensive breakdown showing AI probability percentages, highlighted suspicious sections, and confidence scores. Export results as PDF for documentation.",
  },
  {
    number: "04",
    title: "Take Action",
    description:
      "Make informed decisions with clear, actionable insights. Use our detailed report to verify content authenticity, maintain academic integrity, or ensure original writing.",
  },
]

export const PRICING = {
  title: "Simple, Transparent Pricing",
  subtitle: "Choose the plan that fits your needs. No hidden fees.",
  plans: [
    {
      name: "FREE",
      badge: "Most Popular",
      price: "$0",
      billing: "Forever Free",
      description: "Perfect for occasional checks and personal use",
      features: [
        "5 scans per day",
        "Up to 5,000 characters per scan",
        "Basic AI detection report",
        "95% accuracy rate",
        "Email support",
        "No credit card required",
      ],
      cta: "Start Free",
      variant: "outline" as const,
    },
    {
      name: "PRO",
      badge: "Best Value",
      price: "$29",
      billing: "per month",
      description: "For professionals, educators, and content teams",
      features: [
        "Unlimited scans",
        "Up to 50,000 characters per scan",
        "Advanced detection with highlights",
        "98% accuracy rate",
        "Multiple AI model detection (GPT-4, Claude, Gemini)",
        "PDF export & API access",
        "Batch processing",
        "Priority support",
        "Team collaboration tools",
      ],
      cta: "Start 7-Day Trial",
      variant: "default" as const,
      popular: true,
    },
  ],
}

export const FAQ = [
  {
    question: "How accurate is the AI detection?",
    answer:
      "Our AI detector maintains a 98% accuracy rate for Pro users and 95% for Free users. We continuously train our models on the latest AI-generated content from GPT-4, Claude, Gemini, and other leading AI systems. The detector analyzes over 50 linguistic parameters including sentence structure, word choice patterns, and stylistic consistency.",
  },
  {
    question: "Which AI writing tools can you detect?",
    answer:
      "We can detect content generated by ChatGPT (GPT-3.5, GPT-4, GPT-4 Turbo), Claude (all versions), Google Gemini, Jasper, Copy.ai, and most other AI writing assistants. Our detection models are updated weekly to identify new AI tools and writing patterns.",
  },
  {
    question: "Is my content stored or used for training?",
    answer:
      "Absolutely not. We prioritize your privacy. All submitted content is analyzed in real-time and immediately deleted from our servers after processing. We never store your text, use it for model training, or share it with third parties. Our service is fully GDPR compliant.",
  },
  {
    question: "Can I use this for academic purposes?",
    answer:
      "Yes! Our AI detector is widely used by educators, universities, and students to verify content authenticity. We provide detailed PDF reports suitable for academic documentation. However, we recommend using our tool as part of a comprehensive assessment approach, not as the sole determinant.",
  },
  {
    question: "What if I disagree with the detection results?",
    answer:
      "Our system provides probability scores rather than absolute judgments. If you believe results are inaccurate, you can submit the content for manual review (Pro plan only). We also show which specific sections triggered detection, allowing you to understand and verify our analysis.",
  },
]

export const FOOTER = {
  tagline: "Trusted AI detection for the modern world",
  description:
    "Leading AI content detection platform helping educators, businesses, and content creators maintain authenticity and originality.",
  quickLinks: [
    { label: "Home", href: "#" },
    { label: "Features", href: "#features" },
    { label: "Pricing", href: "#pricing" },
    { label: "How It Works", href: "#how-it-works" },
    { label: "API Documentation", href: "#" },
    { label: "Blog", href: "#" },
  ],
  legal: [
    { label: "Privacy Policy", href: "#" },
    { label: "Terms of Service", href: "#" },
    { label: "Cookie Policy", href: "#" },
  ],
  support: [
    { label: "Help Center", href: "#" },
    { label: "Contact Us", href: "#" },
    { label: "FAQ", href: "#faq" },
    { label: "System Status", href: "#" },
  ],
  social: [
    { label: "Twitter", href: "#", icon: "Twitter" },
    { label: "LinkedIn", href: "#", icon: "Linkedin" },
    { label: "GitHub", href: "#", icon: "Github" },
  ],
  copyright: "© 2025 AI Content Detector. All rights reserved.",
}
